-- ==========================================
-- PESCO MTLMS MAIN DATABASE SCHEMAS
-- SPECS FOR REGIONAL JURISDICTION SYSTEMS
-- ==========================================

-- 1. Create meters Table
CREATE TABLE IF NOT EXISTS public.meters (
  id TEXT PRIMARY KEY,
  "meterNumber" TEXT UNIQUE,
  "serialNumber" TEXT,
  manufacturer TEXT,
  "accuracyClass" TEXT,
  category TEXT,
  status TEXT,
  "stockStatus" TEXT,
  "purchaseDate" TEXT,
  "ctRatio" TEXT,
  "ptRatio" TEXT,
  imei TEXT,
  "simNumber" TEXT,
  "simInstallStatus" TEXT,
  "communicationStatus" TEXT,
  "signalStrength" INTEGER,
  iccid TEXT,
  "networkProvider" TEXT,
  "simInstalledBy" TEXT,
  "simInstallDate" TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create receipts Table
CREATE TABLE IF NOT EXISTS public.receipts (
  id TEXT PRIMARY KEY,
  "receiptNumber" TEXT,
  "dateReceived" TEXT,
  "consumerAccount" TEXT,
  "consumerName" TEXT,
  "meterType" TEXT,
  "meterNumber" TEXT,
  "serialNumber" TEXT,
  make TEXT,
  "receivedFrom" TEXT,
  "reasonForTesting" TEXT,
  "newOrUsed" TEXT,
  "receivedBy" TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create cts Table
CREATE TABLE IF NOT EXISTS public.cts (
  id TEXT PRIMARY KEY,
  "ctNumber" TEXT,
  make TEXT,
  ratio TEXT,
  "accuracyClass" TEXT,
  "dateReceived" TEXT,
  "testDate" TEXT,
  "testResult" TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create pts Table
CREATE TABLE IF NOT EXISTS public.pts (
  id TEXT PRIMARY KEY,
  "ptNumber" TEXT,
  make TEXT,
  ratio TEXT,
  "accuracyClass" TEXT,
  "dateReceived" TEXT,
  "testDate" TEXT,
  "testResult" TEXT,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create cases Table
CREATE TABLE IF NOT EXISTS public.cases (
  id TEXT PRIMARY KEY,
  "caseNumber" TEXT,
  "accountNumber" TEXT,
  "consumerName" TEXT,
  "meterNumber" TEXT,
  "existingMeterDetails" TEXT,
  "newMeterDetails" TEXT,
  "reasonForCommitteeCheck" TEXT,
  "committeeMembers" TEXT[],
  "inspectionDate" TEXT,
  findings TEXT,
  recommendations TEXT,
  "approvalStatus" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create reports Table
CREATE TABLE IF NOT EXISTS public.reports (
  id TEXT PRIMARY KEY,
  "reportNumber" TEXT,
  "meterId" TEXT,
  "testDate" TEXT,
  "consumerName" TEXT,
  "accountNumber" TEXT,
  tariff TEXT,
  "fatherName" TEXT,
  "natureOfConnection" TEXT,
  "meterNumber" TEXT,
  "meterType" TEXT,
  "meterMake" TEXT,
  "serialNumber" TEXT,
  "installationDate" TEXT,
  "removalDate" TEXT,
  readings JSONB,
  "accuracyTest" JSONB,
  discrepancies TEXT[],
  "otherDiscrepancyRemarks" TEXT,
  "checkedBy" TEXT,
  "checkedByDesignation" TEXT,
  "counterSignedBy" TEXT,
  "counterSignedByDesignation" TEXT,
  "approvalDate" TEXT,
  "qrCodeMockUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create auditLogs Table (Supports camelCase for JS client alignment)
CREATE TABLE IF NOT EXISTS public."auditLogs" (
  id TEXT PRIMARY KEY,
  "user" TEXT,
  role TEXT,
  timestamp TEXT,
  action TEXT,
  "oldValue" TEXT,
  "newValue" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Create standards Table
CREATE TABLE IF NOT EXISTS public.standards (
  id TEXT PRIMARY KEY,
  name TEXT,
  "standardValue" TEXT,
  multiplier NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Create todos Table
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- DISABLE ROW LEVEL SECURITY (RLS) FOR PIPELINE BYPASS
-- ==========================================
ALTER TABLE public.meters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."auditLogs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.standards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- REAL-TIME FALLBACK POLICIES IF YOU RE-ENABLE RLS OR TO BYPASS RESTRICTIONS
-- ==========================================
DROP POLICY IF EXISTS "allow_anon_meters" ON public.meters;
CREATE POLICY "allow_anon_meters" ON public.meters FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_receipts" ON public.receipts;
CREATE POLICY "allow_anon_receipts" ON public.receipts FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_cts" ON public.cts;
CREATE POLICY "allow_anon_cts" ON public.cts FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_pts" ON public.pts;
CREATE POLICY "allow_anon_pts" ON public.pts FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_cases" ON public.cases;
CREATE POLICY "allow_anon_cases" ON public.cases FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_reports" ON public.reports;
CREATE POLICY "allow_anon_reports" ON public.reports FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_auditLogs" ON public."auditLogs";
CREATE POLICY "allow_anon_auditLogs" ON public."auditLogs" FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_standards" ON public.standards;
CREATE POLICY "allow_anon_standards" ON public.standards FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "allow_anon_todos" ON public.todos;
CREATE POLICY "allow_anon_todos" ON public.todos FOR ALL TO anon USING (true) WITH CHECK (true);

